[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
day_4 = "65DffTdzK5sRsjtbHS3Mgqa5shf5fJouLpTQC1iJNc42"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
